version: '3.5'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_URL=postgresql://root:password@postgres:5432/postgres
    ports:
      - 8000:8000
    command: pnpm run dev
 
    networks:
      - postgres
    depends_on:
      - postgres
    
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
